---
kind: Template
apiVersion: v1
metadata:
  name: liker
  annotations:
    description: Bare bone template for basic CLI application in Golang.
    tags: golang
    iconClass: icon-go-gopher
labels:
  template: liker
objects:

### IMAGE STREAMS
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: liker-binary
    annotations:
      description: Keeps track of changes in the application image.

- kind: ImageStream
  apiVersion: v1
  metadata:
    name: liker-runtime
    annotations:
      description: Keeps track of changes in the application image.

### BUILD ARTIFACT
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: liker-binary
  spec:
    source:
      type: Git
      git:
        uri: "https://github.com/agajdosi/liker.git"
      contextDir: build-binary
    triggers:
    - type: ConfigChange
    strategy:
      type: Docker
    output:
      to:
        kind: ImageStreamTag
        name: liker-binary:latest

  # BUILD RUNTIME
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: liker-runtime
  spec:
    source:
      type: Git
      git:
        uri: "https://github.com/agajdosi/liker.git"
      contextDir: runtime
      images:
      - from:
          kind: ImageStreamTag
          name: liker-binary:latest
        paths:
        - destinationDir: runtime
          sourcePath: /go/src/github.com/agajdosi/liker/build-binary/build-binary
    triggers:
    - type: ConfigChange
#    - imageChange: {}
#      type: ImageChange
    strategy:
      dockerStrategy:
        from: 
          kind: DockerImage
          name: alpine:latest
    output:
      to:
        kind: ImageStreamTag
        name: liker-runtime:latest

# DEPLOYMENT
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: liker
    annotations:
      description: Defines how to deploy the application server.
  spec:
    strategy:
      type: Recreate
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - liker
        from:
          kind: ImageStreamTag
          name: liker-runtime:latest
    - type: ConfigChange
    replicas: 1
    selector:
      name: liker
    template:
      metadata:
        name: liker
        labels:
          name: liker
      spec:
        containers:
        - name: liker
          image: liker
          env:
          - name: GET_URL
            value: ${GET_URL}
          command:
          - "/liker/build-binary"

parameters:
- name: GET_URL
  description: Which URL will be checked.
  value: http://google.com 
